version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: quantstorm
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
